name: Check style via Diktat

on:
  pull_request:
    branches: [ master ]
  push:

jobs:
  run_diktat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_gradle.yaml
      - name: ls
        run: ls -la -R /home/runner/work/KDex
      - name: Run diktat
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: diktatCheck --no-daemon
      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: ${{ github.workspace }}