name: CI Integration tests

on:
  push:
    branches: [ master ]

jobs:
  setup_gradle:
    uses: ./.github/workflows/ci_setup_gradle.yaml
  intergration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: integrationTest --no-daemon