name: CI Integration tests

on:
  push:
    branches: [ master ]

jobs:
  intergration_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Gradle
        uses: ./.github/workflows/ci_setup_gradle.yaml
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: integrationTest --no-daemon