name: CI build and unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup_gradle:
    uses: ./.github/workflows/ci_setup_gradle.yaml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: build --no-daemon