name: CI build and unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Gradle
        uses: ./.github/workflows/ci_setup_gradle
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: build --no-daemon